version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"







# Future use when the front is ready
    # depends_on:
    #   - frontend

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - backend
